version: '3'
services:
  build:
    image: klakegg/hugo:0.84.1-ext-ubuntu
    volumes:
      - ".:/src"
      - "./public:/target"
  server:
    image: klakegg/hugo:0.84.1-ext-ubuntu
    command: server
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
